[package]
name = "labmand"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
labman-core = { path = "../../crates/labman-core" }
labman-config = { path = "../../crates/labman-config" }
clap = { version = "4.5", features = ["derive"] }
